### PR TITLE
Update on_deliver* and add new `on_session_expired` hook

### PR DESCRIPTION
**Pull request by codeadict**
Add new `on_deliver*` hook variant to include QoS and Retained flag modifiers and new `on_session_expired` hook.

Part of https://github.com/vernemq/vernemq/issues/1346

### CODE REVIEW

**Comment by ioolkos** [comment]
Looks good to me. Thanks :)
One thing I have to understand is how the "retain as publish" thing might interfere in the v5 version of the on_deliver hook you propose. (https://github.com/vernemq/vernemq/blob/d4c54592305d3ff609e6865490e39db3e26538a7/apps/vmq_server/test/vmq_retain_SUITE.erl#L389)

**Comment by codeadict** [comment]
Good point @ioolkos  I'm gonna write a test and check that later. Another thing I'm concerned is that people with already developed plugins and upgrade `vernemq_dev` will have breaking changes. I'm not quite sure what is a good answer here but i've mentioned before that we need a changelog and versioning for this package to avoid these things.

**Comment by ioolkos** [comment]
Thanks, agree. Should we add a tag/release for the vernemq_dev master as is, and then add a tag after your PR is merged?

**Comment by codeadict** [comment]
Thinking about how to express this on the plugin development documentation...

**Comment by ioolkos** [comment]
Created a 1.0.0. release, so I think I can merge this PR.

**Comment by codeadict** [comment]
Sounds good to me @ioolkos . A bit busy today but feel free to merge.

**Pull request merged**
